import { NextRequest, NextResponse } from 'next/server';
import axios from 'axios';
import { auth } from '@clerk/nextjs/server';
import { prisma } from '@/lib/prisma';
import { Connection, PublicKey, TransactionInstruction, TransactionMessage, VersionedTransaction, SystemProgram } from '@solana/web3.js';
import { createTransferInstruction, getAssociatedTokenAddressSync, createSyncNativeInstruction } from '@solana/spl-token';

const SOL_MINT = 'So11111111111111111111111111111111111111112';
const USDC_MINT = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v';
const USDT_MINT = 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB';

// Use the public Jupiter API — quote-api.jup.ag requires an API key
const JUPITER_SWAP_URL = 'https://public.jupiterapi.com/swap';
const JUPITER_INSTRUCTIONS_URL = 'https://public.jupiterapi.com/swap-instructions';

export async function POST(request: NextRequest) {
    try {
        const { userId: clerkId } = await auth();
        const body = await request.json();

        // The client forwards components generated by hook/quote API
        const { quoteResponse, userPublicKey, feeMint, feeStrategy, manualFeeAtoms } = body;

        if (!quoteResponse) {
            return NextResponse.json(
                { error: 'quoteResponse is required.' },
                { status: 400 }
            );
        }

        if (!userPublicKey) {
            return NextResponse.json({ error: 'Missing userPublicKey' }, { status: 400 });
        }

        const FEE_ACCOUNTS: Record<string, string | undefined> = {
            [SOL_MINT]: process.env.PLATFORM_FEE_ACCOUNT_SOL,
            [USDC_MINT]: process.env.PLATFORM_FEE_ACCOUNT_USDC,
            [USDT_MINT]: process.env.PLATFORM_FEE_ACCOUNT_USDT,
        };

        const isManualFee = feeStrategy === 'input' && manualFeeAtoms;

        let finalSwapTransactionBase64: string;

        if (isManualFee) {
            console.info(`[TradeSwapAPI] 🛠️ Building custom pre-swap manual fee transaction. FeeMint: ${feeMint}`);

            const swapPayload = {
                quoteResponse,
                userPublicKey,
                wrapAndUnwrapSol: true,
                computeUnitPriceMicroLamports: 'auto',
                dynamicComputeUnitLimit: true,
            };

            const jupiterRes = await axios.post(JUPITER_INSTRUCTIONS_URL, swapPayload, { timeout: 20000 });
            const instructionsData = jupiterRes.data;

            if (instructionsData.error) {
                return NextResponse.json({ error: instructionsData.error }, { status: 500 });
            }

            const deserializeInstruction = (instruction: any) => {
                if (!instruction) return null;
                return new TransactionInstruction({
                    programId: new PublicKey(instruction.programId),
                    keys: instruction.accounts.map((key: any) => ({
                        pubkey: new PublicKey(key.pubkey),
                        isSigner: key.isSigner,
                        isWritable: key.isWritable,
                    })),
                    data: Buffer.from(instruction.data, "base64"),
                });
            };

            const computeBudgetInstructions = (instructionsData.computeBudgetInstructions || []).map(deserializeInstruction);
            const setupInstructions = (instructionsData.setupInstructions || []).map(deserializeInstruction);
            const swapInstruction = deserializeInstruction(instructionsData.swapInstruction);
            const cleanupInstruction = deserializeInstruction(instructionsData.cleanupInstruction);

            const connection = new Connection(process.env.NEXT_PUBLIC_SOLANA_RPC || 'https://mainnet.helius-rpc.com/?api-key=f5dc817d-eaf2-4a0b-93ff-1836696fa796');

            // Construct manual fee instruction
            let feeInstruction: TransactionInstruction;
            let syncInstruction: TransactionInstruction | undefined;
            const payer = new PublicKey(userPublicKey);
            const feeDestArray = FEE_ACCOUNTS[feeMint as string];

            if (!feeDestArray) {
                return NextResponse.json({ error: 'Platform fee account not configured for input mint' }, { status: 500 });
            }

            const feeDest = new PublicKey(feeDestArray);

            if (feeMint === SOL_MINT) {
                // Send native SOL to the Jupiter Referral WSOL Token Account
                // and sync it so that it reflects in the token balance
                feeInstruction = SystemProgram.transfer({
                    fromPubkey: payer,
                    toPubkey: feeDest,
                    lamports: BigInt(manualFeeAtoms),
                });
                syncInstruction = createSyncNativeInstruction(feeDest);
            } else {
                const sourceAta = getAssociatedTokenAddressSync(new PublicKey(feeMint as string), payer);
                feeInstruction = createTransferInstruction(
                    sourceAta,
                    feeDest,
                    payer,
                    BigInt(manualFeeAtoms)
                );
            }

            const allInstructions = [
                ...computeBudgetInstructions,
                ...setupInstructions,
                feeInstruction,
                syncInstruction,
                swapInstruction,
                ...(cleanupInstruction ? [cleanupInstruction] : [])
            ].filter(Boolean) as TransactionInstruction[];

            const addressLookupTableAccounts = await Promise.all(
                (instructionsData.addressLookupTableAddresses || []).map(async (address: string) => {
                    const accountInfo = await connection.getAddressLookupTable(new PublicKey(address));
                    return accountInfo.value;
                })
            ).then(res => res.filter(a => a !== null));

            const { blockhash } = await connection.getLatestBlockhash();

            const messageV0 = new TransactionMessage({
                payerKey: payer,
                recentBlockhash: blockhash,
                instructions: allInstructions,
            }).compileToV0Message(addressLookupTableAccounts as any);

            const transaction = new VersionedTransaction(messageV0);
            finalSwapTransactionBase64 = Buffer.from(transaction.serialize()).toString('base64');
            console.log('[TradeSwapAPI] ✅ Successfully built custom transaction with pre-swap fee.');

        } else {
            // Standard Jupiter swap using platformFeeBps (output strategy or noc fee)
            const feeAccount = feeMint ? FEE_ACCOUNTS[feeMint as string] : undefined;
            const hasFeeAccount = !!feeAccount && !feeAccount.startsWith('REPLACE_WITH');

            if (hasFeeAccount) {
                console.info(`[TradeSwapAPI] ✅ Platform fee → ${feeStrategy} strategy | Mint: ${feeMint} | Account: ${feeAccount}`);
            } else {
                console.info(`[TradeSwapAPI] ⚠️ No configured referral account for feeMint="${feeMint ?? 'none'}" (strategy: ${feeStrategy ?? 'none'}). Swap proceeds without platform fee.`);
            }

            const swapPayload: Record<string, any> = {
                quoteResponse,
                userPublicKey,
                wrapAndUnwrapSol: true,
                computeUnitPriceMicroLamports: 'auto',
                dynamicComputeUnitLimit: true,
            };

            if (hasFeeAccount) {
                swapPayload.feeAccount = feeAccount;
            }

            console.log('[TradeSwapAPI] 🚀 Sending payload to Jupiter Swap API:', JSON.stringify({
                userPublicKey: swapPayload.userPublicKey,
                feeAccount: swapPayload.feeAccount,
                wrapAndUnwrapSol: swapPayload.wrapAndUnwrapSol
            }));

            const swapResult = await axios.post(JUPITER_SWAP_URL, swapPayload, {
                timeout: 20_000,
                headers: { 'Content-Type': 'application/json' },
            });

            const { swapTransaction } = swapResult.data;

            if (!swapTransaction) {
                console.error('[TradeSwapAPI] ❌ Failed to generate swap transaction from Jupiter');
                return NextResponse.json({ error: 'Failed to generate swap transaction' }, { status: 500 });
            }

            finalSwapTransactionBase64 = swapTransaction;
            console.log('[TradeSwapAPI] ✅ Successfully received standard swapTransaction (base64). Length:', finalSwapTransactionBase64.length);
        }

        // ─── Persist swap intent ──────────────────────────────────────────────────
        let txRecordId = null;
        if (clerkId) {
            const dbUser = await prisma.user.findUnique({ where: { clerkId } });
            if (dbUser) {
                const record = await prisma.transaction.create({
                    data: {
                        userId: dbUser.id,
                        chain: 'solana',
                        type: 'swap',
                        txHash: 'pending_' + Date.now().toString(),
                    },
                });
                txRecordId = record.id;
            }
        }

        return NextResponse.json({ swapTransaction: finalSwapTransactionBase64, recordId: txRecordId }, { status: 200 });

    } catch (error: any) {
        const detail = error?.response?.data ?? error.message;
        console.error('[TradeSwapAPI] Route error:', detail);
        return NextResponse.json(
            { error: 'Internal server error', details: typeof detail === 'string' ? detail : JSON.stringify(detail) },
            { status: 500 }
        );
    }
}
